### ISSUE TITLE
Having trouble installing on Raspbian Stretch and Jessie

### ISSUE THREAD

**Issue by pageauc** [mcmclx/py3exiv2#1]
Trying to install py3exiv2 onto a raspberry pi using

sudo pip3 install py3exiv2

Install errors out per below.  Also see log at bottom.  I have checked setuptools and that appears OK

Any help would be appreciated

Thanks Claude ...

---------------------------------------------
building 'libexiv2python' extension

creating build/temp.linux-armv7l-3.4

creating build/temp.linux-armv7l-3.4/src

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c src/exiv2wrapper.cpp -o build/temp.linux-armv7l-3.4/src/exiv2wrapper.o -g

cc1plus: warning: command line option â-Wstrict-prototypesâ is valid for C/ObjC but not for C++

In file included from src/exiv2wrapper.cpp:27:0:

src/exiv2wrapper.hpp:32:27: fatal error: exiv2/image.hpp: No such file or directory

 #include "exiv2/image.hpp"

                           ^

compilation terminated.

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-yq2gn5az/py3exiv2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6sofkvu8-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-yq2gn5az/py3exiv2
Storing debug log for failure in /root/.pip/pip.log

------------------------------------------

Here is the log

 $ sudo cat /root/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip3 run on Wed Nov 29 15:07:16 2017
Downloading/unpacking pyexiv2
  Getting page https://pypi.python.org/simple/pyexiv2/
  Could not fetch URL https://pypi.python.org/simple/pyexiv2/: 404 Client Error: Not Found (pyexiv2 does not exist)
  Will skip URL https://pypi.python.org/simple/pyexiv2/ when looking for download links for pyexiv2
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for pyexiv2:
  * https://pypi.python.org/simple/pyexiv2/
  Getting page https://pypi.python.org/simple/pyexiv2/
  Could not fetch URL https://pypi.python.org/simple/pyexiv2/: 404 Client Error: Not Found (pyexiv2 does not exist)
  Will skip URL https://pypi.python.org/simple/pyexiv2/ when looking for download links for pyexiv2
  Could not find any downloads that satisfy the requirement pyexiv2
Cleaning up...
No distributions at all found for pyexiv2
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for pyexiv2

**Comment by pageauc** [comment]
I have successfully built library on a raspberry pi per your repo instructions rather that trying to use pip

    git clone https://github.com/mcmclx/py3exiv2.git
    sudo apt-get install -y python-all-dev
    sudo apt-get install -y libexiv2-dev
    sudo apt-get install -y libboost-python-dev
    sudo apt-get install -y g++
    cd  py3exiv2
    python3 configure.py
    ./build.sh
    sudo ./build.sh -i

/usr/lib/python3/dist-packages/libexiv2python.so  was successfully installed but had to use sudo rather than ./build.sh -i

Was able to import exiv2 in python3. Seems to work OK but still doing some testing

Thanks for the repo and instructions were sufficient.

Claude ...

**Comment by mcmclx** [comment]
Sorry for not seeing this until after you fixed your issue, but glad it's working for you!  As I hope is clear, this is just a fork of the [master](https://code.launchpad.net/~vincent-vandevyvre/py3exiv2/trunk), and issues should ideally be brought up there.
