### ISSUE TITLE
Compile hangs on Raspberry pi with 512 mb memory including 1024 swap space 

### ISSUE THREAD

**Issue by pageauc** [mcmclx/py3exiv2#2]
I use pyexiv2 in my pi-timolo project that runs under python 2 or 3.  There is a pip install for python2 but for python3, I have written a bash script to automate install of dependencies, git clone, configure, compile, install your project.  This works fine on RPI's with 1 GB memory and there are no problems other than taking a bit of time to compile.

A user on a RPI zero with 512 memory complained that compile would hang.  I tested and even with 1024 mb of swap the compile consumes all memory and hangs.  Also swap memory is very slow since RPI OS is run on SD card.
Are there any ways to reduce the amount of memory required to compile so it can compile with 512 of RAM memory?
Thanks Claude ...

**Comment by mcmclx** [comment]
Unfortunately, this is an old clone of the bzr repo here:  https://code.launchpad.net/~vincent-vandevyvre/py3exiv2/trunk  Maybe you can reach out to the owner there to see if they can help you out?  Sorry I can't be of more assistance!
